### ISSUE TITLE
Chunk loading bug - BedWars1058 Plugin

### ISSUE THREAD

**Issue by Weark** [Imanity-Software/ImanitySpigot3-git#127]
### Expected behavior

The hologram was supposed to always show the 3 lines of the hologram, and the 4th line the ore rotating.
Print of how it was for it to work:
https://i.imgur.com/j59FjmD.png

### Observed/Actual behavior

The holograms are disappearing when players move away from them, right after the chunk unloads and the player comes back, sometimes only a few lines of the hologram load, sometimes disappearing entirely.
3 Prints showing the bugs: https://imgur.com/a/Rs8SoHX

### Steps/models to reproduce

1- Setup a BedWars1058 Plugin arena.
2- Start a BedWars arena.
3- Move away from the diamond and emerald generator holograms and then return to them.

### Plugin list

WorldEdit, PlaceholderAPI, WorldGuard, LuckPerms, Vault, Citizens, DeluxeMenus, BedWars1058, DecentHolograms, ViaVersion, ProtocolLib, FAWE

### ImanitySpigot3 version

2022.05.3 BUILD 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by Weark** [comment]
I found out that it's not just in BedWars, but in several plugins that have ArmorStand system.
Example of cosmetics from GadgetsMenu.
My Vision: https://i.imgur.com/0vdfbFE.png
View of players who joined after me already has the cosmetic activated: https://i.imgur.com/fiX5UXc.png

See that the cosmetic is buggy so it goes in later.

**Comment by Whizyyy** [comment]
Is this also happening without ViaVersion on your server?

**Comment by Weark** [comment]
Yes, even removing via version and all players using version 1.8.9 this happens.

Looks like a problem with charging the ArmorStand .

**Comment by LeeGodSRC** [comment]
Can you try to disable `parallelEntityTracking` in imanity/config.yml?

**Comment by SxHundered** [comment]
### I am sorry, but my English is not that perfect, so try to understand:

I had the same issue, 

I am using a plugin that uses SQL as database, and the problem is my SQL connection was connected in clustering database which has high latency.
**(After moving SQL locally, the issue was gone)**

What I think is:

The player has to request data via SQL, and **Bedwars1058** uses main thread to get all necessary data from MySQL.

I have made few tests: I tried to load data from MySQL at (PlayerLoginEvent, Which is before firing PlayerJoinEvent)
What happened is the player spends time BEFORE entering the server, and after a while I have joined immediately and chunks loaded so fast.

Conclusion:

I believe that players has to be loaded into the server, including all other plugins that use main thread in playerjoinevent, playerloginevent, etc... 
Meaning: **You won't be loaded into the server until all tasks that run by the plugins in main thread done!**

**SUGGESTION**: try to host your MySQL server to the nearest possible point so that you don't take much time to get response from MySQL
OR try to cache your data via Redis, which will speed things much faster! (If you have a custom plugin).

**Comment by Weark** [comment]
> Você pode tentar desabilitar `parallelEntityTracking`em imanity/config.yml?

Problem solved: https://i.imgur.com/TEQQsxi.jpeg
