### ISSUE TITLE
Issue with chunk loading and TPS drop

### ISSUE THREAD

**Issue by Daniels32** [Imanity-Software/ImanitySpigot3-git#132]
### Expected behavior

.

### Observed/Actual behavior

.

### Steps/models to reproduce

I want use ImanitySpigot but I can't due issues. In video is issue with chunk loading and TPS drop https://www.youtube.com/watch?v=ghQ547XIQ5Y&ab_channel=DanielSawicki I have same problem on SkyWars. Currently I using LightSpigot Lite and I don't have this issue.

### Plugin list

In video.

### ImanitySpigot3 version

2022.05.1 LTS BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

.

**Comment by LeeGodSRC** [comment]
Can you provide a spark report inbetween the time of loading the world?

**Comment by Daniels32** [comment]
https://spark.lucko.me/2wDohqBfxP

**Comment by LeeGodSRC** [comment]
Can you try to enable `asyncLightUpdates.enabled`?

**Comment by Daniels32** [comment]
I did but Server is overloaded with it when I only join arena, in console "Can't keep up! Is the server overloaded? Running 5593ms or 111 ticks behind". I can't do timings due very low TPS and overloading.

**Comment by LeeGodSRC** [comment]
Can you do another spark report? since from the current spark report it doesn't seems to have asyncLightUpdates enabled.

**Comment by Daniels32** [comment]
I can't do spark report with asyncLightUpdates enabled due server was overloaded when I joined to arena.

**Comment by Whizyyy** [comment]
We received another report about the same issue and you both have less than 1GB of RAM available for your server. Please give more RAM to your server, 1GB is insufficiant, then try again

**Comment by Daniels32** [comment]
I tried but it didn't help. I had 3 and 4 GB RAM with enabled and disabled AsyncLightUpdates. chunks loaded little better but still to long and it look weird, lowest TPS was 17.99.

**Comment by xpghard** [comment]
> I tried but it didn't help. I had 3 and 4 GB RAM with enabled and disabled AsyncLightUpdates. chunks loaded little better but still to long and it look weird, lowest TPS was 17.99.

can you send spark profile when you try run your server on 3/4 gb of ram

**Comment by Daniels32** [comment]
https://spark.lucko.me/SkjBiGObjh

**Comment by xpghard** [comment]
When you increased the ram I don't see any problems with the server. Could you record these lags and send a video?

> https://spark.lucko.me/SkjBiGObjh

**Comment by SxHundered** [comment]
### I am sorry, but my English is not that perfect, so try to understand:

**I had the same issue,**

I am using a plugin that uses SQL as database, and the problem is my SQL connection was connected in clustering database which has high latency.
**(After moving SQL locally, the issue was gone)**

**What I think is:**

The player has to request data via SQL, and **Bedwars1058** uses main thread to get all necessary data from MySQL.

I have made few tests: I tried to load data from MySQL at (PlayerLoginEvent, Which is before firing PlayerJoinEvent)
What happened is the player spends time **BEFORE** entering the server, and after a while I have joined immediately and chunks loaded so fast.

**Conclusion:**

I believe that players has to be loaded into the server, including all other plugins that use main thread in playerjoinevent, playerloginevent, etc...
Meaning: You won't be loaded into the server until all tasks that run by the plugins in main thread done!

**SUGGESTION: try to host your MySQL server to the nearest possible point so that you don't take much time to get response from MySQL
OR try to cache your data via Redis, which will speed things much faster! (If you have a custom plugin).**

**Comment by xpghard** [comment]
> ### I am sorry, but my English is not that perfect, so try to understand:
> **I had the same issue,**
> 
> I am using a plugin that uses SQL as database, and the problem is my SQL connection was connected in clustering database which has high latency. **(After moving SQL locally, the issue was gone)**
> 
> **What I think is:**
> 
> The player has to request data via SQL, and **Bedwars1058** uses main thread to get all necessary data from MySQL.
> 
> I have made few tests: I tried to load data from MySQL at (PlayerLoginEvent, Which is before firing PlayerJoinEvent) What happened is the player spends time **BEFORE** entering the server, and after a while I have joined immediately and chunks loaded so fast.
> 
> **Conclusion:**
> 
> I believe that players has to be loaded into the server, including all other plugins that use main thread in playerjoinevent, playerloginevent, etc... Meaning: You won't be loaded into the server until all tasks that run by the plugins in main thread done!
> 
> **SUGGESTION: try to host your MySQL server to the nearest possible point so that you don't take much time to get response from MySQL OR try to cache your data via Redis, which will speed things much faster! (If you have a custom plugin).**

If your English is not very good I recommend using this translator. It's the best one I've found. https://www.deepl.com/translator

**Comment by LeeGodSRC** [comment]
closed due to inactivity.
