### ISSUE TITLE
ServerSideHitDetection causes teleportation throwing NullPointerException

### ISSUE THREAD

**Issue by iSilviu-debug** [Imanity-Software/ImanitySpigot3-git#68]
### Expected behavior

I expect the player to be teleported to another world.

### Observed/Actual behavior

Around the player I see only the void and an error appears in the console.

https://paste.gg/p/anonymous/5d093987e35e448bab948853b3af1d63

### Steps/models to reproduce

Create a plugin that teleports the player to another world with a command. In my case:

```
Player player = ...;
player.teleport(getWaitingLocation(), PlayerTeleportEvent.TeleportCause.PLUGIN);
```

### Plugin list

Only my plugin *a bedwars plugin*

### ImanitySpigot3 version

`spigotJarVersion: 2021.11.1 LTS BUILD 5`

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

Before updating to the new version, the server was running fine.

A lot of the performance I had in the "2021.09.3 BUILD 5" version is different than it is now.
When I enter, the cpu load is quite high (I put everything in async), the first time it takes a while to enter..
I would like some advice, better java 16 or java 8 on this case?

*The server I am talking about has allocated 512MB of ram since it is a bedwars mini-server*

Thanks for reading my issue! 🌵

**Comment by LeeGodSRC** [comment]
This error seems to be occur by ServerSideHitDetection which is a incomplete experimental feature, please disable it in the config in order to fix the problem. and please read the comments above options before you randomly turn everything on and off

And on the note `When I enter, the cpu load is quite high (I put everything in async)`
It is normal that cpu load is higher compare to no async enabled since you are allocating more threads to your server
Try to disable some that may not be effective for your server to free up cpu usage.

**Comment by iSilviu-debug** [comment]
God, I never knew it was for that function. Thanks for the information!

**Comment by xpghard** [comment]
After testing, I am unable to repeat the bug. It has been a while so I think it has been fixed.
