### ISSUE TITLE
Performances issues : Tiles still tick when chunk is unloaded

### ISSUE THREAD

**Issue by NivixX** [Imanity-Software/ImanitySpigot3-git#99]
### Expected behavior

When a chunk is unloaded, the tiles doesn't tick

### Observed/Actual behavior

When a chunk is loaded the tile will still tick (forever)

### Steps/models to reproduce

**Pretty easy and fast**

1. Install https://www.spigotmc.org/resources/entitydetection-tile-entity-support.20588/
(It's optional, if you are doing a timings you will see that hoppers still tick even if nobody is around)

2. Place hoppers and verify that it's loaded with the command /detect search hopper
![image](https://user-images.githubusercontent.com/5229597/161376467-bb7f73a4-5b27-4735-a40a-7479fd8835f7.png)

3. Leave the area so the chunk are supposed to unload

4. If you redo a scan with the above command or check timings, you will notice that hopper still tick
![image](https://user-images.githubusercontent.com/5229597/161376610-ed885ef2-1748-4852-9ef4-08c53180cf8f.png)

Note: it's not systematic (it happens 7/10) and when it's happen, hoppers will tick forever.
If you try with tacospigot, you will see that when you leave the area, the detection will tell you that not any hopper is loaded

### Plugin list

EntityDetection
Viaversion
Worldedit
Spark

### ImanitySpigot3 version

2022.03.1 BUILD 1

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

I already did some tickets and issues by the fact I recently got huge performances issue. I think I have enough evidences that show there is something wrong with tiles that didn't happened before (it has been 2 years I'm using ISpigot and I can confirm that I never had these issues long time ago)

**Comment by LeeGodSRC** [comment]
I don't think you actually compared your result with TacoSpigot 1.8.8... You are just randomly clicking the agreements without actually reading it or testing it before agreed.
There is 3 possibility this could happen
1. And the most likely being: The hopper was placed in spawn.
- In Minecraft Server, spawn with 16x16 region will never be unloaded, so hopper doesn't disappear could happen in any fork
- You can try to disable `keep-spawn-loaded` in paper.yml and try again.
2. You have `doChunkUnload` disabled in imanity world config
- If chunk don't unload, tile entity don't unload.
3. The way you tested is misleading.
- Leaving the region until you can't see doesn't equal it's actually unloaded on server side
- Video explaination: https://youtu.be/Tijd9JnNgNA

Out of 3 of these possibility, **There most be 1 fits your scenario**, please do more testing and researching before reporting and blindly believe this is caused by a fork.
